In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,31],[7,8,9,32]],
    [[11,12,13,33],[14,15,16,34],[17,18,19,35]],
    [[21,22,23,36],[24,25,26,37],[27,28,29,38]],
])

El escalar no tiene transpuesta

In [3]:
escalar_t = escalar.T

AttributeError: 'float' object has no attribute 'T'

In [4]:
vector_t = vector.T
print(vector_t)

[3 4 5 6]


## Matriz transpuesta

In [6]:
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
matriz.T

array([[1, 3, 5],
       [2, 4, 6]])

## Tensor

In [8]:
tensor

array([[[ 1,  2,  3, 30],
        [ 4,  5,  6, 31],
        [ 7,  8,  9, 32]],

       [[11, 12, 13, 33],
        [14, 15, 16, 34],
        [17, 18, 19, 35]],

       [[21, 22, 23, 36],
        [24, 25, 26, 37],
        [27, 28, 29, 38]]])

In [9]:
tensor.T

array([[[ 1, 11, 21],
        [ 4, 14, 24],
        [ 7, 17, 27]],

       [[ 2, 12, 22],
        [ 5, 15, 25],
        [ 8, 18, 28]],

       [[ 3, 13, 23],
        [ 6, 16, 26],
        [ 9, 19, 29]],

       [[30, 33, 36],
        [31, 34, 37],
        [32, 35, 38]]])